name: Build

on:
  push:
    branches:
      - main
      - cibuild

jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: |
          brew install libomp
          ./build_gmp.sh ios
          mkdir build_prover_ios && cd build_prover_ios
          cmake .. -GXcode -DTARGET_PLATFORM=IOS -DCMAKE_INSTALL_PREFIX=../package_ios
          xcodebuild -destinations='platform=iOS' -scheme rapidsnarkStatic -project rapidsnark.xcodeproj -configuration Release
