name: Build

on:
  push:
    branches:
      - main
      - cibuild

jobs:
  build:
    runs-on: macos-13-xlarge
    steps:
      - run: |
            uname -a
            xcode-select -p
            brew install libomp
            find /opt/homebrew -name omp.h
            mdfind -name omp.h
